[project]
name = "mcl-core"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "aiohttp",
    "elevate>=0.1.3",
    "loguru",
    "msal[broker]>=1.33.0",
    "psutil",
    "pyyaml>=6.0.2",
]
